[RT classification]
onnxFileName = model/germline/v1.14/germline-ramp-8128462_shuffle_300K_ckpt_260000.onnx
useSerializedModel = 1
trtWorkspaceSizeMB = 2000
numInferTreadsPerGpu = 2
useGPUs = 1
gpuid = 0

[debug]
logFileFolder = .

[ensemble]
ensembleSize = 7
randomSeed = 1000
referenceRows = 5
sampleHeights = 100
shuffleAllSamples = false

[general]
tfrecord = 1
compressed = 1
outputInOneFile = 0
numUncomprThreads = 8
uncomprBufSizeGB = 1
outputFileName = call_variants
numConversionThreads = 2
numExampleFiles = 40

# exampleFile 1 = /90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0001.tfrecord
# exampleFile 2 = /90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0002.tfrecord
# exampleFile 3 = /90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0003.tfrecord

exampleFile	1	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0001.tfrecord
exampleFile	2	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0002.tfrecord
exampleFile	3	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0003.tfrecord
exampleFile	4	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0004.tfrecord
exampleFile	5	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0005.tfrecord
exampleFile	6	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0006.tfrecord
exampleFile	7	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0007.tfrecord
exampleFile	8	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0008.tfrecord
exampleFile	9	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0009.tfrecord
exampleFile	10	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0010.tfrecord
exampleFile	11	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0011.tfrecord
exampleFile	12	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0012.tfrecord
exampleFile	13	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0013.tfrecord
exampleFile	14	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0014.tfrecord
exampleFile	15	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0015.tfrecord
exampleFile	16	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0016.tfrecord
exampleFile	17	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0017.tfrecord
exampleFile	18	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0018.tfrecord
exampleFile	19	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0019.tfrecord
exampleFile	20	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0020.tfrecord
exampleFile	21	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0021.tfrecord
exampleFile	22	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0022.tfrecord
exampleFile	23	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0023.tfrecord
exampleFile	24	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0024.tfrecord
exampleFile	25	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0025.tfrecord
exampleFile	26	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0026.tfrecord
exampleFile	27	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0027.tfrecord
exampleFile	28	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0028.tfrecord
exampleFile	29	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0029.tfrecord
exampleFile	30	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0030.tfrecord
exampleFile	31	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0031.tfrecord
exampleFile	32	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0032.tfrecord
exampleFile	33	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0033.tfrecord
exampleFile	34	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0034.tfrecord
exampleFile	35	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0035.tfrecord
exampleFile	36	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0036.tfrecord
exampleFile	37	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0037.tfrecord
exampleFile	38	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0038.tfrecord
exampleFile	39	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0039.tfrecord
exampleFile	40	=	/90daydata/xu_alfalfabreeding/system_from_home/msi/UG100/08_make_examples/0040.tfrecord
