[RT classification]
onnxFileName = /project/xu_alfalfabreeding/system_from_home/msi/UG100/07_model/model.ckpt-890000.dyn_1500.onnx
useSerializedModel = 1
trtWorkspaceSizeMB = 2000
numInferTreadsPerGpu = 2
useGPUs = 1
gpuid = 0

[debug]
logFileFolder = .

[ensemble]
ensembleSize = 7
randomSeed = 1000
referenceRows = 5
sampleHeights = 100
shuffleAllSamples = false

[general]
tfrecord.gz = 1
compressed = 1
outputInOneFile = 0
numUncomprThreads = 8
uncomprBufSizeGB = 1
outputFileName = call_variants
numConversionThreads = 2
numExampleFiles = 40

# notes use exampleFile1 instead of exampleFile 1
# use sep by space " " instead to use tab
exampleFile1 = 0001.tfrecord.gz
exampleFile2 = 0002.tfrecord.gz
exampleFile3 = 0003.tfrecord.gz
exampleFile4 = 0004.tfrecord.gz
exampleFile5 = 0005.tfrecord.gz
exampleFile6 = 0006.tfrecord.gz
exampleFile7 = 0007.tfrecord.gz
exampleFile8 = 0008.tfrecord.gz
exampleFile9 = 0009.tfrecord.gz
exampleFile10 = 0010.tfrecord.gz
exampleFile11 = 0011.tfrecord.gz
exampleFile12 = 0012.tfrecord.gz
exampleFile13 = 0013.tfrecord.gz
exampleFile14 = 0014.tfrecord.gz
exampleFile15 = 0015.tfrecord.gz
exampleFile16 = 0016.tfrecord.gz
exampleFile17 = 0017.tfrecord.gz
exampleFile18 = 0018.tfrecord.gz
exampleFile19 = 0019.tfrecord.gz
exampleFile20 = 0020.tfrecord.gz
exampleFile21 = 0021.tfrecord.gz
exampleFile22 = 0022.tfrecord.gz
exampleFile23 = 0023.tfrecord.gz
exampleFile24 = 0024.tfrecord.gz
exampleFile25 = 0025.tfrecord.gz
exampleFile26 = 0026.tfrecord.gz
exampleFile27 = 0027.tfrecord.gz
exampleFile28 = 0028.tfrecord.gz
exampleFile29 = 0029.tfrecord.gz
exampleFile30 = 0030.tfrecord.gz
exampleFile31 = 0031.tfrecord.gz
exampleFile32 = 0032.tfrecord.gz
exampleFile33 = 0033.tfrecord.gz
exampleFile34 = 0034.tfrecord.gz
exampleFile35 = 0035.tfrecord.gz
exampleFile36 = 0036.tfrecord.gz
exampleFile37 = 0037.tfrecord.gz
exampleFile38 = 0038.tfrecord.gz
exampleFile39 = 0039.tfrecord.gz
exampleFile40 = 0040.tfrecord.gz